parameters:
    simple_bus.rabbit_mq_bundle_bridge.error_handling.log_level: "critical"
    simple_bus.rabbit_mq_bundle_bridge.error_handling.log_message: "Failed to handle a message"

services:
    simple_bus.rabbit_mq_bundle_bridge.error_logging_event_subscriber:
        class: SimpleBus\RabbitMQBundleBridge\EventListener\LogErrorWhenMessageConsumptionFailed
        arguments:
            - @logger
            - %simple_bus.rabbit_mq_bundle_bridge.error_handling.log_level%
            - %simple_bus.rabbit_mq_bundle_bridge.error_handling.log_message%
        tags:
            - { name: kernel.event_subscriber }
